<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>DotVector.QuickStart</AssemblyName>
    <RootNamespace>DotVector.Examples.QuickStart</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\DotVector.Core\DotVector.Core.csproj" />
  </ItemGroup>

</Project>
