# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dotvector_pb2 as dotvector__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dotvector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorServiceStub(object):
    """============================================================================
    DotVector gRPC API (M9)

    Wire 形态约定：
    - vectors 使用 packed bytes (float32 little-endian)，避免 repeated float 在
    大维度场景下的 length-prefix 开销，并对 SIMD 解码友好。
    - filter 使用 FilterCodec 序列化的 bytes（不展开为递归 message），可与本机
    codec 对称且对 AOT 友好。
    - payload 使用 map<string, ScalarValue>，每个值是 oneof 标量，避免 google.protobuf.Any。
    - 所有主键以 string id 形式传输；服务端按集合的 KeyType 解析为 int/long/Guid/string。
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/dotvector.v1.VectorService/Ping',
                request_serializer=dotvector__pb2.PingRequest.SerializeToString,
                response_deserializer=dotvector__pb2.PingResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/dotvector.v1.VectorService/CreateCollection',
                request_serializer=dotvector__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=dotvector__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/dotvector.v1.VectorService/DeleteCollection',
                request_serializer=dotvector__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=dotvector__pb2.DeleteCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/dotvector.v1.VectorService/ListCollections',
                request_serializer=dotvector__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=dotvector__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.Upsert = channel.unary_unary(
                '/dotvector.v1.VectorService/Upsert',
                request_serializer=dotvector__pb2.UpsertRequest.SerializeToString,
                response_deserializer=dotvector__pb2.UpsertResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/dotvector.v1.VectorService/Delete',
                request_serializer=dotvector__pb2.DeleteRequest.SerializeToString,
                response_deserializer=dotvector__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/dotvector.v1.VectorService/Search',
                request_serializer=dotvector__pb2.SearchRequest.SerializeToString,
                response_deserializer=dotvector__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/dotvector.v1.VectorService/Get',
                request_serializer=dotvector__pb2.GetRequest.SerializeToString,
                response_deserializer=dotvector__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Scroll = channel.unary_unary(
                '/dotvector.v1.VectorService/Scroll',
                request_serializer=dotvector__pb2.ScrollRequest.SerializeToString,
                response_deserializer=dotvector__pb2.ScrollResponse.FromString,
                _registered_method=True)


class VectorServiceServicer(object):
    """============================================================================
    DotVector gRPC API (M9)

    Wire 形态约定：
    - vectors 使用 packed bytes (float32 little-endian)，避免 repeated float 在
    大维度场景下的 length-prefix 开销，并对 SIMD 解码友好。
    - filter 使用 FilterCodec 序列化的 bytes（不展开为递归 message），可与本机
    codec 对称且对 AOT 友好。
    - payload 使用 map<string, ScalarValue>，每个值是 oneof 标量，避免 google.protobuf.Any。
    - 所有主键以 string id 形式传输；服务端按集合的 KeyType 解析为 int/long/Guid/string。
    ============================================================================

    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=dotvector__pb2.PingRequest.FromString,
                    response_serializer=dotvector__pb2.PingResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=dotvector__pb2.CreateCollectionRequest.FromString,
                    response_serializer=dotvector__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=dotvector__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=dotvector__pb2.DeleteCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=dotvector__pb2.ListCollectionsRequest.FromString,
                    response_serializer=dotvector__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=dotvector__pb2.UpsertRequest.FromString,
                    response_serializer=dotvector__pb2.UpsertResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=dotvector__pb2.DeleteRequest.FromString,
                    response_serializer=dotvector__pb2.DeleteResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=dotvector__pb2.SearchRequest.FromString,
                    response_serializer=dotvector__pb2.SearchResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=dotvector__pb2.GetRequest.FromString,
                    response_serializer=dotvector__pb2.GetResponse.SerializeToString,
            ),
            'Scroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Scroll,
                    request_deserializer=dotvector__pb2.ScrollRequest.FromString,
                    response_serializer=dotvector__pb2.ScrollResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dotvector.v1.VectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dotvector.v1.VectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorService(object):
    """============================================================================
    DotVector gRPC API (M9)

    Wire 形态约定：
    - vectors 使用 packed bytes (float32 little-endian)，避免 repeated float 在
    大维度场景下的 length-prefix 开销，并对 SIMD 解码友好。
    - filter 使用 FilterCodec 序列化的 bytes（不展开为递归 message），可与本机
    codec 对称且对 AOT 友好。
    - payload 使用 map<string, ScalarValue>，每个值是 oneof 标量，避免 google.protobuf.Any。
    - 所有主键以 string id 形式传输；服务端按集合的 KeyType 解析为 int/long/Guid/string。
    ============================================================================

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/Ping',
            dotvector__pb2.PingRequest.SerializeToString,
            dotvector__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/CreateCollection',
            dotvector__pb2.CreateCollectionRequest.SerializeToString,
            dotvector__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/DeleteCollection',
            dotvector__pb2.DeleteCollectionRequest.SerializeToString,
            dotvector__pb2.DeleteCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/ListCollections',
            dotvector__pb2.ListCollectionsRequest.SerializeToString,
            dotvector__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/Upsert',
            dotvector__pb2.UpsertRequest.SerializeToString,
            dotvector__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/Delete',
            dotvector__pb2.DeleteRequest.SerializeToString,
            dotvector__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/Search',
            dotvector__pb2.SearchRequest.SerializeToString,
            dotvector__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/Get',
            dotvector__pb2.GetRequest.SerializeToString,
            dotvector__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dotvector.v1.VectorService/Scroll',
            dotvector__pb2.ScrollRequest.SerializeToString,
            dotvector__pb2.ScrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
